version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gosec
    - gocritic
    - revive
    - gocognit
    - funlen
    - lll
    - misspell
  settings:
    misspell:
      ignore-rules:
        - exportfs
    lll:
      line-length: 250
    funlen:
      lines: 300
      statements: 300
    gocognit:
      min-complexity: 100
    revive:
      rules:
        - name: var-naming
          disabled: true
        - name: increment-decrement
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: indent-error-flow
          disabled: true
        - name: empty-block
          disabled: true
        - name: exported
          disabled: true
        - name: if-return
          disabled: true

formatters:
  enable:
    - gofumpt
