run:
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - gosec
    - gocritic
    - revive
    - gocognit
    - funlen
    - lll
    - misspell

linters-settings:
  lll:
    line-length: 120