name: Actionlint

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4.1.7
      - name: Check workflow files
        uses: ravsamhq/action-actionlint@1360a27665447978768d0623e6b9903c467946e8 # v0.1.0
